services:
  backend:
    build: ./backend
    container_name: backend-flor
    expose:
      - "3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: flor
      DB_PASSWORD: flor123
      DB_NAME: prestamos

  mysql:
    image: mysql:8
    container_name: mysql-flor
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: prestamos
      MYSQL_USER: flor
      MYSQL_PASSWORD: flor123
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx-flor
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mysql_data:
